[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "openai-responses-server"
version = "0.1.0"
description = "A proxy server that converts between different OpenAI-compatible API formats"
authors = [
    { name = "Orin", email = "" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
dependencies = [
    "fastapi>=0.68.0",
    "uvicorn>=0.15.0",
    "httpx>=0.24.0",
    "python-dotenv>=0.19.0",
    "pydantic>=1.8.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "black>=21.0",
    "flake8>=3.9",
]

[tool.hatch.build.targets.wheel]
packages = ["src/openai_responses_server"]

[tool.hatch.build]
exclude = [
    "tests/*",
    "examples/*",
    "docs/*",
]

[project.urls]
Documentation = "https://github.com/orin/openai-responses-server/docs"
Source = "https://github.com/orin/openai-responses-server"

[project.scripts]
openai-responses-server = "openai_responses_server.cli:main"